server:
  port: 8080

external-apis:
  classes-service:
    urls:
      host: 'https://localhost:8081'
      paths:
        classesByCourseIdPath: "/api/classes?courseId="

    api-key:
  documents-service:
    urls:
      host: 'https://document-service-0q2q.onrender.com' #http://document-service, onrender.com on deployment
      paths:
#        docByCourseIdPath: "/api/documents?courseId="
         docByCourseIdPath: "/api/courseDocuments/getAllByCourseId/{courseId}"
    api-key:
  db-connector:
    urls:
      host: "https://old-seminar-2-back-4hjd.onrender.com"
      paths:
        getCourses:
         "/api/course/all"
        getCourseById:
         "/api/course/byId/{courseId}"
        addCourse:
         "/api/course/add"
        updateCourse:
         "/api/course/update/{courseId}"
        deleteCourse:
         "/api/course/delete/{courseId}"
