server:
  port: 8080

external-apis:
  classes-service:
    urls:
      host: https://localhost:8081
      paths:
        classesByCourseIdPath: "/api/classes?courseId="

    api-key:
  documents-service:
    urls:
      host: https://localhost:8082 #http://document-service, onrender.com on deployment
      paths:
        docByCourseIdPath: "/api/documents?courseId="
    api-key:
  db-connector:
    urls:
      host: https://old-seminar-2-back-4hjd.onrender.com/api/db/courses
      paths:
        getCourses:
         "/all"
        getCourseById:
         "/ById/"
        addCourse:
         "/add"
        updateCourse:
         "/update"
        deleteCourse:
         "/delete"
